version: "3.8"

services:
  backend:
    build: ./SA_Backend
    container_name: student-backend
    ports:
      - "5001:5001"
    env_file:
      - ./SA_Backend/.env
    depends_on:
      - mongo
    volumes:
      - ./SA_Backend:/app
    networks:
      - app-network

  frontend:
    build: ./SA_Frontend
    container_name: student-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./SA_Frontend:/app
    networks:
      - app-network

  mongo:
    image: mongo
    container_name: student-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
